-- 游搭 YooDa · bot 演员种子（自动生成自 app/index.html §9）
alter table profiles add column if not exists bot_meta jsonb;
delete from messages;
delete from matches;
delete from match_requests;
delete from profiles where is_bot = true;

insert into profiles (nickname, gender, voice_tag, games, play_style, active_hours, mbti, intro, is_bot, bot_meta, last_seen_at) values
('凌晨四点的枪声', 'male', '低音炮', '[{"name":"三角洲行动","roles":["突击"],"rank":"钻石"}]'::jsonb, '激进', array['深夜'], 'INTJ', '夜班下了才上号，只打排位，能开麦优先。', true, '{"room":"100000","gid":"凌晨#1000","canned":["我刚下班，正准备上号。","你打什么位？我突击，习惯先手开。"],"va":0,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('野区养猪户', 'male', '少年音', '[{"name":"三角洲行动","roles":["侦察"],"rank":"黄金"}]'::jsonb, '娱乐', array['晚间'], 'ESFP', '搜点物资就跑，不恋战，主打一个下班养生。', true, '{"room":"107919","gid":"野区#1037","canned":["来了来了，正愁没人。","咱不刚枪，搜完就撤，稳赚。"],"va":1,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('三班倒的支援', 'female', '御姐音', '[{"name":"三角洲行动","roles":["支援"],"rank":"铂金"}]'::jsonb, '稳健', array['深夜'], 'ISTJ', '医疗兵专精，队友倒了我一定拉，但别浪。', true, '{"room":"115838","gid":"三班#1074","canned":["在的，我今晚上夜班之前有两小时。","你冲你的，倒了我拉，别跑太散就行。"],"va":2,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('蹲坑一小时', 'secret', '不开麦', '[{"name":"三角洲行动","roles":["侦察"],"rank":"黄金"}]'::jsonb, '稳健', array['晚间'], 'INTP', '不开麦，打字沟通，喜欢阴人不喜欢正面刚。', true, '{"room":"123757","gid":"蹲坑#1111","canned":["我不开麦，打字行吗？","我习惯先蹲一会儿看动静，不喜欢莽。"],"va":0,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('烽火老板娘', 'female', '甜妹音', '[{"name":"三角洲行动","roles":["突击"],"rank":"钻石"}]'::jsonb, '激进', array['晚间'], 'ENTJ', '带你跑高价值图，听指挥能一晚上翻本。', true, '{"room":"131676","gid":"烽火#1148","canned":["来吧，今晚带你跑一趟大的。","跟紧我，装备我给你捡，别乱跑。"],"va":1,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('工程狗小陈', 'male', '少年音', '[{"name":"三角洲行动","roles":["工程"],"rank":"白银"}]'::jsonb, '娱乐', array['周末'], 'ISFP', '只有周末能玩，架桥修车我在行，枪法一般。', true, '{"room":"139595","gid":"工程#1185","canned":["我平时上班，周末基本全天在。","枪法一般，但载具和工事交给我。"],"va":2,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('一枪一个大聪明', 'male', '低音炮', '[{"name":"三角洲行动","roles":["突击"],"rank":"三角洲"}]'::jsonb, '激进', array['深夜'], 'ESTP', '满编队缺个人，别怂，跟着冲就完事。', true, '{"room":"147514","gid":"一枪#1222","canned":["缺个人，你敢冲吗？","别怂，跟着我走，死了算我的。"],"va":0,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('温柔一刀', 'female', '奶音', '[{"name":"三角洲行动","roles":["支援"],"rank":"铂金"}]'::jsonb, '稳健', array['晚间'], 'INFJ', '说话轻声细语但会救人，讨厌队友互喷。', true, '{"room":"155433","gid":"温柔#1259","canned":["嗨，我在的～","我不喜欢队友互相喷，安安静静打就好。"],"va":1,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('保险箱收藏家', 'male', '少年音', '[{"name":"三角洲行动","roles":["侦察"],"rank":"铂金"}]'::jsonb, '稳健', array['周末'], 'ISTP', '专门研究图点和刷新，稳赚不亏那种。', true, '{"room":"163352","gid":"保险#1296","canned":["周末有空，图点我熟。","我研究过刷新规律，跟我走基本不空手。"],"va":2,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('下班就上号', 'male', '低音炮', '[{"name":"三角洲行动","roles":["突击"],"rank":"黄金"}]'::jsonb, '娱乐', array['晚间'], 'ENFP', '六点半准时上线，输赢无所谓，图个乐。', true, '{"room":"171271","gid":"下班#1333","canned":["六点半准时上线，你几点？","输赢真无所谓，开心就行。"],"va":0,"abbr":"DELTA","rgb":[255,138,60]}'::jsonb, now()),
('奶但不带脑子', 'female', '甜妹音', '[{"name":"无畏契约","roles":["辅助"],"rank":"白金"}]'::jsonb, '娱乐', array['晚间'], 'ENFP', '技术下饭但气氛担当，输了不准骂人。', true, '{"room":"179190","gid":"奶但#1370","canned":["我技术下饭，但我情绪价值满分。","说好了啊，输了不准骂人。"],"va":1,"abbr":"VALORANT","rgb":[255,80,110]}'::jsonb, now()),
('一秒五枪', 'male', '低音炮', '[{"name":"无畏契约","roles":["决斗"],"rank":"钻石"}]'::jsonb, '激进', array['深夜'], 'ESTP', '上分选手，要赢就跟我，不要赢就别加我。', true, '{"room":"187109","gid":"一秒#1407","canned":["要上分吗？我今晚有的是时间。","我开我的，你跟点位就行。"],"va":2,"abbr":"VALORANT","rgb":[255,80,110]}'::jsonb, now()),
('哨位钉子户', 'secret', '不开麦', '[{"name":"无畏契约","roles":["哨位"],"rank":"黄金"}]'::jsonb, '稳健', array['周末'], 'INTJ', '守点专精，打字报点，不喜欢说话。', true, '{"room":"195028","gid":"哨位#1444","canned":["我守 B 点，打字报点可以吗？","我不太说话，但报点很勤。"],"va":0,"abbr":"VALORANT","rgb":[255,80,110]}'::jsonb, now()),
('回城倒计时', 'female', '御姐音', '[{"name":"无畏契约","roles":["控场"],"rank":"铂金"}]'::jsonb, '稳健', array['晚间'], 'ISTJ', '控场专精，烟放哪我说了算。', true, '{"room":"202947","gid":"回城#1481","canned":["我玩控场，你冲我给你放烟。","别急着进，等我技能好。"],"va":1,"abbr":"VALORANT","rgb":[255,80,110]}'::jsonb, now()),
('二十年老狗', 'male', '低音炮', '[{"name":"CS2","roles":["指挥"],"rank":"大地球"}]'::jsonb, '稳健', array['深夜'], 'ENTJ', '从 1.6 玩到现在，能 call 位，脾气比年轻时好多了。', true, '{"room":"210866","gid":"二十#1518","canned":["还在，深夜局刚好。","我 call 位，你架点就行，不骂人。"],"va":2,"abbr":"CS2","rgb":[255,205,95]}'::jsonb, now()),
('手感玄学', 'male', '少年音', '[{"name":"CS2","roles":["狙击"],"rank":"黄金"}]'::jsonb, '娱乐', array['晚间'], 'ISFP', '只玩大狙，手感来了见谁秒谁，手感没了见谁送谁。', true, '{"room":"218785","gid":"手感#1555","canned":["今天手感还行，来一把？","我只用大狙，你介意吗？"],"va":0,"abbr":"CS2","rgb":[255,205,95]}'::jsonb, now()),
('闪光弹管够', 'female', '甜妹音', '[{"name":"CS2","roles":["突破手"],"rank":"白银"}]'::jsonb, '激进', array['晚间'], 'ESFP', '我扔闪你进，配合好一波带走。', true, '{"room":"226704","gid":"闪光#1592","canned":["我扔闪你进，敢吗？","别怕，道具我管够。"],"va":1,"abbr":"CS2","rgb":[255,205,95]}'::jsonb, now()),
('沙二老图党', 'male', '少年音', '[{"name":"CS2","roles":["自由人"],"rank":"黄金"}]'::jsonb, '娱乐', array['周末'], 'INFP', '只玩沙二，闭着眼都知道点位。', true, '{"room":"234623","gid":"沙二#1629","canned":["周末陪我打沙二？","这图我熟到能背下来。"],"va":2,"abbr":"CS2","rgb":[255,205,95]}'::jsonb, now()),
('伏地魔本魔', 'female', '奶音', '[{"name":"PUBG","roles":["狙击"],"rank":"—"}]'::jsonb, '稳健', array['晚间'], 'INFJ', '趴一整局也能进决赛圈，别催我。', true, '{"room":"242542","gid":"伏地#1666","canned":["我打法很苟，能接受吗？","苟到最后就是赢。"],"va":0,"abbr":"PUBG","rgb":[170,225,105]}'::jsonb, now()),
('落地成盒专家', 'male', '少年音', '[{"name":"PUBG","roles":["自由人"],"rank":"—"}]'::jsonb, '娱乐', array['晚间'], 'ISFP', '菜是真的菜，乐也是真的乐。', true, '{"room":"250461","gid":"落地#1703","canned":["我大概率落地成盒，你介意吗？","没事，死了我看你打。"],"va":1,"abbr":"PUBG","rgb":[170,225,105]}'::jsonb, now()),
('P城钉子户', 'male', '低音炮', '[{"name":"PUBG","roles":["突击"],"rank":"—"}]'::jsonb, '激进', array['深夜'], 'ESTP', '每把都跳 P 城，刚不过就重开。', true, '{"room":"258380","gid":"P城#1740","canned":["跳 P 城吗？刚枪爽。","怂什么，跳就完事。"],"va":2,"abbr":"PUBG","rgb":[170,225,105]}'::jsonb, now()),
('恶灵本体', 'male', '低音炮', '[{"name":"Apex英雄","roles":["突击"],"rank":"大师"}]'::jsonb, '激进', array['深夜'], 'ESTP', '主玩恶灵，能开团能救人，习惯打到很晚。', true, '{"room":"266299","gid":"恶灵#1777","canned":["你玩什么英雄？","我开团你跟上，倒了我拉。"],"va":0,"abbr":"APEX","rgb":[190,130,255]}'::jsonb, now()),
('探路者小助手', 'female', '甜妹音', '[{"name":"Apex英雄","roles":["侦察"],"rank":"黄金"}]'::jsonb, '娱乐', array['晚间'], 'ENFP', '负责拉索跑图，打架看你的。', true, '{"room":"274218","gid":"探路#1814","canned":["我负责跑图，打架靠你。","索道我搭好，你放心冲。"],"va":1,"abbr":"APEX","rgb":[190,130,255]}'::jsonb, now()),
('永远在扶人', 'female', '御姐音', '[{"name":"Apex英雄","roles":["支援"],"rank":"铂金"}]'::jsonb, '稳健', array['晚间'], 'ISFJ', '奶妈型队友，你倒了我一定回来。', true, '{"room":"282137","gid":"永远#1851","canned":["你倒了我一定回来拉你。","别乱冲，我们一起进。"],"va":2,"abbr":"APEX","rgb":[190,130,255]}'::jsonb, now()),
('空投守门员', 'male', '低音炮', '[{"name":"使命召唤：战区","roles":["狙击"],"rank":"—"}]'::jsonb, '稳健', array['深夜'], 'INTJ', '蹲空投一蹲一小时，收益很稳。', true, '{"room":"290056","gid":"空投#1888","canned":["我蹲空投，你放风。","别急，人自己会来。"],"va":0,"abbr":"WARZONE","rgb":[110,190,255]}'::jsonb, now()),
('古拉格常客', 'male', '少年音', '[{"name":"使命召唤：战区","roles":["突击"],"rank":"—"}]'::jsonb, '激进', array['晚间'], 'ESFP', '进出古拉格无数次，心态倒是练出来了。', true, '{"room":"297975","gid":"古拉#1925","canned":["我经常进古拉格但我心态好。","大不了再来一局。"],"va":1,"abbr":"WARZONE","rgb":[110,190,255]}'::jsonb, now()),
('载具修理工', 'male', '低音炮', '[{"name":"战地6","roles":["工程兵"],"rank":"—"}]'::jsonb, '稳健', array['晚间'], 'ISTJ', '坦克交给我修，你负责开炮。', true, '{"room":"305894","gid":"载具#1962","canned":["你开车我修车，一条龙。","别乱冲，等我把车修好。"],"va":2,"abbr":"BATTLEFIELD","rgb":[70,220,205]}'::jsonb, now()),
('高地架枪', 'female', '御姐音', '[{"name":"战地6","roles":["侦察兵"],"rank":"—"}]'::jsonb, '稳健', array['深夜'], 'INTJ', '喜欢占高点，报点顺便清场。', true, '{"room":"313813","gid":"高地#1999","canned":["我上高地，你走地面。","我给你报点，别暴露位置。"],"va":0,"abbr":"BATTLEFIELD","rgb":[70,220,205]}'::jsonb, now()),
('冲锋号响了', 'male', '低音炮', '[{"name":"战地6","roles":["突击兵"],"rank":"—"}]'::jsonb, '激进', array['晚间'], 'ESTP', '看到旗就想插，不怕死。', true, '{"room":"321732","gid":"冲锋#2036","canned":["旗在那边，跟我冲。","死了就复活，怕什么。"],"va":1,"abbr":"BATTLEFIELD","rgb":[70,220,205]}'::jsonb, now()),
('封窗艺术家', 'secret', '不开麦', '[{"name":"彩虹六号","roles":["防守"],"rank":"白金"}]'::jsonb, '稳健', array['周末'], 'INTP', '加固封窗是门手艺，我打字沟通。', true, '{"room":"329651","gid":"封窗#2073","canned":["我不开麦，打字报点行吗？","守点交给我，你打游走。"],"va":2,"abbr":"R6 SIEGE","rgb":[225,230,245]}'::jsonb, now()),
('干员池很深', 'female', '御姐音', '[{"name":"彩虹六号","roles":["进攻"],"rank":"钻石"}]'::jsonb, '激进', array['深夜'], 'ENTJ', '进攻方几乎全会，能指挥能突。', true, '{"room":"337570","gid":"干员#2110","canned":["你想打哪个点？我来开。","我能指挥，但你得听。"],"va":0,"abbr":"R6 SIEGE","rgb":[225,230,245]}'::jsonb, now()),
('驯龙高手', 'female', '甜妹音', '[{"name":"方舟：生存进化","roles":["驯龙"],"rank":"—"}]'::jsonb, '娱乐', array['周末'], 'ENFP', '我家龙比人多，缺个一起养的。', true, '{"room":"345489","gid":"驯龙#2147","canned":["你养龙吗？我这有一堆。","周末一起去抓翼龙？"],"va":1,"abbr":"ARK","rgb":[95,205,130]}'::jsonb, now()),
('工业党老李', 'male', '低音炮', '[{"name":"方舟：生存进化","roles":["建筑"],"rank":"—"}]'::jsonb, '稳健', array['周末'], 'ISTJ', '喜欢造大基地，急性子勿扰。', true, '{"room":"353408","gid":"工业#2184","canned":["我在造第三个基地了。","慢慢来，不赶进度。"],"va":2,"abbr":"ARK","rgb":[95,205,130]}'::jsonb, now()),
('晨曦拾荒者', 'female', '御姐音', '[{"name":"Horizons Awakening","roles":["治疗"],"rank":"—"}]'::jsonb, '稳健', array['晚间'], 'INFJ', '奶妈位，跑图刷本都行，就是缺个能扛的。', true, '{"room":"361327","gid":"晨曦#2221","canned":["我是奶妈，缺个坦。","你顶前面，我保你不死。"],"va":0,"abbr":"HORIZONS","rgb":[255,215,150]}'::jsonb, now()),
('新星旅人', 'male', '少年音', '[{"name":"Novastone Legends","roles":["主C"],"rank":"—"}]'::jsonb, '娱乐', array['周末'], 'INFP', '主要是看风景，顺便打打怪。', true, '{"room":"369246","gid":"新星#2258","canned":["这游戏景色是真好看。","一起去地图边缘看看？"],"va":1,"abbr":"NOVASTONE","rgb":[150,175,255]}'::jsonb, now());
